package cn.ashersu.omni.model.edit;

import cn.ashersu.omni.model.Usage;

import java.util.List;

/**
 * A list of edits generated by OpenAI
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
public class EditResult {

    /**
     * The type of object returned, should be "edit"
     */
    private String object;

    /**
     * The creation time in epoch milliseconds.
     */
    private long created;

    /**
     * A list of generated edits.
     */
    private List<EditChoice> choices;

    /**
     * The API usage for this request
     */
    private Usage usage;
    
    public EditResult() {
    }
    
    public EditResult(String object, long created, List<EditChoice> choices, Usage usage) {
        this.object = object;
        this.created = created;
        this.choices = choices;
        this.usage = usage;
    }
    
    public String getObject() {
        return object;
    }
    
    public void setObject(String object) {
        this.object = object;
    }
    
    public long getCreated() {
        return created;
    }
    
    public void setCreated(long created) {
        this.created = created;
    }
    
    public List<EditChoice> getChoices() {
        return choices;
    }
    
    public void setChoices(List<EditChoice> choices) {
        this.choices = choices;
    }
    
    public Usage getUsage() {
        return usage;
    }
    
    public void setUsage(Usage usage) {
        this.usage = usage;
    }
}
