package cn.ashersu.omni.model.edit;

/**
 * An edit generated by OpenAi
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
public class EditChoice {

    /**
     * The edited text.
     */
    private String text;

    /**
     * This index of this completion in the returned list.
     */
    private Integer index;
    
    public EditChoice() {
    }
    
    public EditChoice(String text, Integer index) {
        this.text = text;
        this.index = index;
    }
    
    public String getText() {
        return text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    public Integer getIndex() {
        return index;
    }
    
    public void setIndex(Integer index) {
        this.index = index;
    }
}
